export {
  type AuthorizationCallback,
  type AuthorizationDefinition,
  type ConnectionAuthDefinition,
  type ConnectionAuthProvider,
  type ConnectionAuthResolver,
  type ConnectionAuthorizationChallenge,
  ConnectionAuthorizationFailedError,
  type ConnectionAuthorizationFailedErrorOptions,
  ConnectionAuthorizationRequiredError,
  type ConnectionAuthorizationRequiredErrorOptions,
  type ConnectionPrincipal,
  type HeadersDefinition,
  type InteractiveAuthorizationDefinition,
  type JsonValue,
  type McpClientConnectionDefinition,
  type NonInteractiveAuthorizationDefinition,
  type OpenAPIConnectionDefinition,
  type OpenAPISpecSource,
  type TokenResult,
  type ToolFilterDefinition,
  defineInteractiveAuthorization,
  defineMcpClientConnection,
  defineOpenAPIConnection,
  isConnectionAuthorizationFailedError,
  isConnectionAuthorizationRequiredError,
} from "../../src/public/connections/index.ts";
